### PR TITLE
Submission for Ethereum Blockchain Connector - Sharepoint bounty

### PR DESCRIPTION
**Pull request by panjevic**
## Purpose
This sample is intended to showcase the usage of Ethereum blockchain as immutable log in auditing purposes to keep track of changes made on the SharePoint list.
We will be tracking Id of the modified item, modified date, email and display name of the user making changes and storing it on the blockchain.

### CODE REVIEW

**Comment by mmercuri** [comment]
From the issue "send metadata about the change to a smart contract that will be used as a decentralized audit."    This is about auditing the changes to files.

You should be using a different action, specifically "The content of the file.
When a file is created or modified (properties only"

You will need to change this to use this action for this to be approved and should be auditing the actions/changes.  Your sample includes filenames and other metadata in their raw (vs. hashed).  If you include values here, they should be hashed (see feedback on your other submission).

Otherwise - nice job, I like that you're incorporating two of the bounties together.

**Comment by panjevic** [comment]
@mmercuri I've updated the solution according to your comments. 
Logic app is now tracking changes made to the document library. 
Smart contract contains hashes of file content, file metadata and hashed modified by email. It also contains the timestamp (in form of ticks) and an enum stating whether the document has been created or modified. I haven't been able to get this from SharePoint connector, so I'm tracking in the smart contract if this is a first log for the specific document, and deciding a type of change based on that.

**Comment by panjevic** [comment]
One more thing, I made a mistake by including files from the other bounty (ebc-computervision) so please take care when merging the PR.

**Comment by mmercuri** [comment]
panjevic's entry was accepted.

**Pull request merged**
