### PR TITLE
Submission for ebc-forms-basic

### LINKED ISSUE #1: Ethereum Blockchain Connector - Microsoft Forms (basic)
### The Challenges from Microsoft
The general objective of these bounties are to build solutions that are part of the community to help others building applications, by making samples leveraging various components both as part of the Ethereum ecosystem and part of the services provided by Microsoft.

* Help the community by providing rich samples of most common scenarios
* Demonstrate how to integrate to services in Azure 

### Reward
The reward amount for this bounty is 200 DAI.  This bounty is valid until a completed submission is accepted or the bounty deadline of April 30, 2019 expires.  The solution will be reviewed for completeness and should be free of errors.  The submissions will be reviewed every 48 hours.

### Bounty - Ethereum Blockchain Connector - Microsoft Forms (basic)
Build a sample that will contain a Microsoft Form that will submit some data, which will be written to a smart contract on an Ethereum blockchain backend.  To do this:
* Create a new Microsoft Form instance with at least one data field.
* Create an Ethereum based smart contract with a method to receive this data.
* Create an Ethereum blockchain instance, private networks work best.
* Use the Ethereum Blockchain Connector (see below) (Logic App) to connect the submission from the Microsoft Form to the smart contract.
* Document the solution with steps to recreate.  A simple README.md will suffice.
* Add the solution the [ebc-forms-basic](https://github.com/Azure-Samples/bc-community-samples/tree/master/ebc-forms-basic) directory in this repository.

### Instructions
Documentation to help with this challenge can be found here:
* [Getting started with Microsoft Forms](https://support.office.com/en-us/forms)
* [Getting started with Ethereum Connectors](https://docs.microsoft.com/en-us/connectors/blockchainethereum/)
* [VS Code](https://code.visualstudio.com) for development
* [Simple Ethereum POA network on Azure](https://github.com/caleteeter/smartcontractdev/blob/master/example1-setup.md)

If you don't already have an Azure account, you can [create a free one](https://azure.microsoft.com/en-us/free/) here to start building!

### About Microsoft Forms
Microsoft Forms is a simple, lightweight app that lets you easily create surveys, quizzes, and polls. In educational institutions, it can be used to create quizzes, collect feedback from teachers and parents, or plan class and staff activities. In business organizations, it can be used to collect customer feedback, measure employee satisfaction, improve your product or business, or organize company events.

### Communication
Find us on [Discord](https://discord.gg/5RS8Ca4) and/or drop your questions here.

### Additional Terms of Service
This is a Skills Contest open only to persons who are of legal age to form a binding contract (Age of Majority) in the jurisdiction where they reside at the time of entry. Each person must also qualify with the Gitcoin Account Terms of Use available at https://gitcoin.co/legal/terms and the GitHub  Account Terms of Service available at https://help.github.com/en/articles/github-terms-of-service to enter. Last submission accepted by 11:59:59 p.m. PT on April 30, 2019.  See [Full Official Rules](https://github.com/Azure-Samples/bc-community-samples/tree/master/Gitcoin_Hackathon_Rules.pdf) for details.

### PR DESCRIPTION
**Pull request by touhonoob**
## Purpose
To fix #1 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```
## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Get the code from https://github.com/touhonoob/bc-community-samples/tree/ebc-forms-basic/ebc-forms-basic then follow README.md

### CODE REVIEW

**Comment by caleteeter** [comment]
Sorry we have a PR that is nearly accepted, just getting a source file, but the solution was validated. @touhonoob

**Comment by touhonoob** [comment]
@caleteeter Could you please reconsider? I believe my submission is much more clear to a beginner than the first submission.

**Comment by StevenJNPearce** [comment]
@caleteeter You can give it to this one; I hit a bug on mine that I don't understand; it might be an issue in Nethereum. For next couple of days I don't have time to look into it.

**Comment by mmercuri** [comment]
Tounoob - Your sample uses an email address which is put on the chain, which actually should never be done because it is personally identifiable information (PII).  Because the blockchain is immutable, this can cause significant problems with government regulations, e.g. GDPR in Europe.    Can you please change email address to something non-PII, such as "Registration Code"?

**Comment by touhonoob** [comment]
@mmercuri The pull request is updated to be GDPR compliant. Please re-evaluate: https://github.com/Azure-Samples/bc-community-samples/pull/33/commits/220dfb5af496b4fb4fb1e9a1bd1a3f83c7c9c4b6

**Pull request merged**
