### PR TITLE
Tolling App Submission

### PR DESCRIPTION
**Pull request by drdgvhbh**
## Purpose

Submission for the Toll Device App Challenge #18 

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
Follow the Read me

### CODE REVIEW

**Comment by caleteeter** [comment]
This is great work @drdgvhbh !  This was selected as the winner.  We will get this merged and payout sent your way.

**Comment by drdgvhbh** [comment]
Amazing! Thank you very much.

**Comment by JakubNer** [comment]
Well done Ryan!  Really great demo with the NFC, pretty much exactly what was asked for 👍 .

**Comment by drdgvhbh** [comment]
Thanks Jakub!

**Pull request merged**
